// app/head.js
export default function Head() {
    return (
        <>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Täsk | Simple as fäck</title>
            <meta name="description" content="Generated by create next app" />
            {/* Tu peux ajouter d’autres meta ici */}
        </>
    );
}