import { Geist, Geist_Mono, Instrument_Sans } from "next/font/google";
import "@/styles/globals.css";
import "quill/dist/quill.snow.css";
import "react-quill/dist/quill.snow.css";
import { instrumentSans } from "@/utils/font";

export const metadata = {
  title: "Täsk | Simple as fäck",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={instrumentSans.className}>{children}</body>
    </html>
  );
}
