import "@/styles/globals.css";
import { instrumentSans } from "@/utils/font";
import moment from "moment-timezone";
moment.tz.setDefault("Europe/Paris");

export const metadata = {
  title: "Täsk | Simple as fäck",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={instrumentSans.className}>{children}</body>
    </html>
  );
}
